name: Make-RADIO

on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'URL'
        required: true
        default: ''
        
      twrp_URL:
        description: 'twrp_URL'
        required: false
        default: ''
        
      zip_name:
        description: 'zip_name'
        required: true
        default: 'fw-oplus9r-oos1-final.zip'
        
      payload:
        description: 'is payload？'
        required: true
        default: 'true'
        type: boolean

      images:
        description: 'img'
        required: true
        default: 'abl aop bluetooth cmnlib cmnlib64 devcfg dsp featenabler hyp imagefv keymaster logo mdm_oem_stanvbk modem multioem multiimgoem qupfw spunvm storsec tz uefisecapp xbl xbl_config xbl_lp5 xbl_config_lp5'
        
        #"apusys audio_dsp ccu dpm dtbo gpueb gz lk logo mcf_ota mcupm md1img mvpu_algo pi_img preloader_raw scp spmfw sspm tee vbmeta vcp"#redmi-k50
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
          
    - name: 下载
      if: github.event.inputs.payload == 'false'
      run: |
        aria2c -x10 -U "netdisk" "${{ github.event.inputs.URL }}" -o aaaa.zip || wget -U "netdisk" "${{ github.event.inputs.URL }}" -o aaaa.zip
        mkdir firmware-update
        
    - name: 解包~提取(payload)
      if: github.event.inputs.payload == 'true'    
      run: |
        unzip -q aaaa.zip payload.bin
        rm -rf aaaa.zip 
        pip install git+https://github.com/5ec1cff/payload-dumper
        chmod 777 *
        echo "images: $${{ github.event.inputs.images }}"
        payload_dumper --out firmware-update --partitions "${{ github.event.inputs.images }}" "${{ github.event.inputs.URL }}" 
        
        git clone https://github.com/zhlhlf/android_flash_scripts -b main zhlhlf --depth=1
        mv firmware-update zhlhlf/
        cd zhlhlf
        rm -rf README.md .git
        if [ "${{ github.event.inputs.twrp_URL }}" ];then aria2c -x6 -U "netdisk" "${{ github.event.inputs.twrp_URL }}" -o recovery.img -d firmware-update ; fi 

    - name: 解包~提取(color)
      if: github.event.inputs.payload == 'false'
      run: |
        unzip -v "aaaa.zip"
        unzip "aaaa.zip" firmware-update/* -d ./ || echo "压缩包根目录没有firmware-update"
        unzip "aaaa.zip" system_vendor* -d ./ || echo "压缩包根目录没有system_vendor.zip"
        unzip system_vendor* firmware-update/* -d ./ || echo "666" 
        mkdir zhlhlf
        cp -r firmware-update zhlhlf/       
                         
    - name: 打包上传到wetransfer
      run: |
        cd zhlhlf
        sha256sum firmware-update/*
        sha256sum firmware-update/* > firmware-update/by-zhlhlf.txt
        du -h firmware-update/*
        echo "$(date +%Y-%m-%d-%H)" >> "firmware-update/by-zhlhlf.txt"
        echo "${{ github.event.inputs.URL }}" >> "firmware-update/by-zhlhlf.txt"
        zip -qr "${{ github.event.inputs.zip_name }}" *     
        rm -rf 666
        mkdir 666
        mv "${{ github.event.inputs.zip_name }}" 666
        curl -sL https://raw.githubusercontent.com/zhlhlf/text/refs/heads/main/upload/upload.sh | bash -s ${{ secrets.RCK }} 

