name: Make-RADIO

on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'URL'
        required: true
        default: ''
        
env:
  transfer: true
  partition: color #color
  hhhh: "boot,dtbo"
#"abl,aop,bluetooth,cmnlib,cmnlib64,devcfg,dsp,featenabler,hyp,imagefv,keymaster,logo,mdm_oem_stanvbk,modem,multioem,multiimgoem,qupfw,spunvm,storsec,tz,uefisecapp,xbl,xbl_config,xbl_lp5,xbl_config_lp5" #oneplus9r
#"apusys,audio_dsp,ccu,dpm,dtbo,gpueb,gz,lk,logo,mcf_ota,mcupm,md1img,mvpu_algo,pi_img,preloader_raw,scp,spmfw,sspm,tee,vbmeta,vcp"#redmi-k50

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
          
    - name: 下载
      run: |
        aria2c -x16 -j5 -s16 -U "netdisk;11.36.0;iPhone14ProMax;ios-iphone;16.0;zh_CN" -d tmp "${{ github.event.inputs.URL }}" -o "${{ github.event.inputs.name }}" || wget -U "netdisk;11.36.0;iPhone14ProMax;ios-iphone;16.0;zh_CN" "${{ github.event.inputs.URL }}" -d tmp/
        
    - name: 解包~提取(payload)
      if: env.partition == 'payload'    
      run: |
        unzip ./tmp/*.zip -d ./                   
        chmod 7777 payload-dumper-go
        ./payload-dumper-go -p $hhhh -o zhlhlf/firmware-update payload.bin
        ls zhlhlf/firmware-update

    - name: 解包~提取(color)
      if: env.partition == 'color'    
      run: |
        zz=$(ls tmp/*.zip)
        unzip -v $zz
        unzip ./tmp/$zz system_vendor.zip -d ./                         
        unzip system_vendor.zip -d ./ 
        cp -r firmware-update zhlhlf/                            
                         
    - name: 打包上传到wetransfer
      if: env.transfer == 'true'      
      run: |
        ls zhlhlf
        cd zhlhlf
        zip -q -r RADIO-oplus9r.zip *      
        curl -sL https://git.io/file-transfer | sh     
        sudo ./transfer wet RADIO-oplus9r.zip
        
        
