name: Make-RADIO

on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'URL'
        required: true
        default: ''
      hhh:
        description: 'URL'
        required: true
        default: 'abl,aop,bluetooth,cmnlib,cmnlib64,devcfg,dsp,featenabler,hyp,imagefv,keymaster,logo,mdm_oem_stanvbk,modem,multioem,qupfw,spunvm,storsec,tz,uefisecapp,xbl,xbl_config'
        
env:
  transfer: true
  release: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
          
    - name: 下载
      run: |
        aria2c -x16 -j5 -s16 -U "netdisk;11.36.0;iPhone14ProMax;ios-iphone;16.0;zh_CN" -d tmp "${{ github.event.inputs.URL }}" -o "${{ github.event.inputs.name }}" || wget -U "netdisk;11.36.0;iPhone14ProMax;ios-iphone;16.0;zh_CN" "${{ github.event.inputs.URL }}" -d tmp/
        unzip ./tmp/*.zip -d ./
        ls
        
    - name: 配置环境解包
      run: |
        chmod 7777 payload-dumper-go
        ./payload-dumper-go -p ${{ github.event.inputs.URL }} -o zhlhlf/firmware-update payload.bin
        ls output
        ls zhlhlf/firmware-update
        zip RADIO-oplus9r.zip zhlhlf/*
                         
    - name: 上传到transfer
      if: env.transfer == 'true'      
      run: |
        curl -sL https://git.io/file-transfer | sh
        ls tmp      
        sudo ./transfer wet RADIO-oplus9r.zip
