name: Make-RADIO

on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'URL'
        required: true
        default: ''
        
env:
  transfer: true
  release: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
          
    - name: Initialization environment 
      run: |
        git clone https://github.com/vm03/payload_dumper.git
        pip install bsdiff4
        pip install protobuf

    - name: 下载
      run: |
        aria2c -x16 -j5 -s16 -U "netdisk;11.36.0;iPhone14ProMax;ios-iphone;16.0;zh_CN" -d tmp "${{ github.event.inputs.URL }}" -o "${{ github.event.inputs.name }}" || wget -U "netdisk;11.36.0;iPhone14ProMax;ios-iphone;16.0;zh_CN" "${{ github.event.inputs.URL }}" -d tmp/
        unzip ./tmp/*.zip -d ./
        ls
        
    - name: 配置解包环境
      run: |
        python payload_dumper/payload_dumper.py payload.bin
        mv payload_dumper/output ./output
        mv output/abl.img zhlhlf/firmware-update/abl.img
        mv output/aop.img zhlhlf/firmware-update/aop.img
        mv output/bluetooth.img zhlhlf/firmware-update/bluetooth.img
        mv output/cmnlib.img zhlhlf/firmware-update/cmnlib.img
        mv output/cmnlib64.img zhlhlf/firmware-update/cmnlib64.img
        mv output/devcfg.img zhlhlf/firmware-update/devcfg.img
        mv output/dsp.img zhlhlf/firmware-update/dsp.img
        mv output/featenabler.img zhlhlf/firmware-update/featenabler.img
        mv output/hyp.img zhlhlf/firmware-update/hyp.img
        mv output/imagefv.img zhlhlf/firmware-update/imagefv.img
        mv output/keymaster.img zhlhlf/firmware-update/keymaster.img
        mv output/logo.img zhlhlf/firmware-update/logo.img
        mv output/mdm_oem_stanvbk.img zhlhlf/firmware-update/mdm_oem_stanvbk.img
        mv output/modem.img zhlhlf/firmware-update/modem.img
        mv output/multiimgoem.img zhlhlf/firmware-update/multiimgoem.img
        mv output/qupfw.img zhlhlf/firmware-update/qupfw.img
        mv output/spunvm.img zhlhlf/firmware-update/spunvm.img
        mv output/storsec.img zhlhlf/firmware-update/storsec.img
        mv output/tz.img zhlhlf/firmware-update/tz.img
        mv output/uefisecapp.img zhlhlf/firmware-update/uefisecapp.img
        mv output/xbl.img zhlhlf/firmware-update/xbl.img
        mv output/xbl_config.img zhlhlf/firmware-update/xbl_config.img
        ls zhlhlf/firmware-update
        zip -rf RADIO-oplus9r.zip zhlhlf/*
                         
    - name: 上传到transfer
      if: env.transfer == 'true'      
      run: |
        curl -sL https://git.io/file-transfer | sh
        ls tmp      
        sudo ./transfer wet RADIO-oplus9r.zip
